// ============================================================
// PHRASES - every unique Japanese phrase used in the app.
// Each phrase is referenced by its short id from quizData below,
// and also used directly on the Extras page (extra.html).
// ============================================================
const phrases = {
    ohayou:            { romaji: "Ohayou gozaimasu",                         audio: "おはようございます.wav" },
    konnichiwa:        { romaji: "Konnichiwa",                               audio: "こんにちは.wav" },
    konbanwa:          { romaji: "Konbanwa",                                 audio: "こんばんは.wav" },
    sumimasen:         { romaji: "Sumimasen",                                audio: "すみません.wav" },
    onegaishimasu:     { romaji: "Onegaishimasu",                            audio: "お願いします.wav" },
    douzo:             { romaji: "Douzo",                                    audio: "どうぞ.wav" },
    hai:               { romaji: "Hai",                                      audio: "はい.wav" },
    iie:               { romaji: "Iie",                                      audio: "いいえ.wav" },
    daijoubu:          { romaji: "Daijoubu desu",                            audio: "大丈夫です.wav" },
    arigatou:          { romaji: "Arigatou gozaimasu",                       audio: "ありがとうございます.wav" },
    ekiDoko:           { romaji: "Eki wa doko desu ka?",                     audio: "駅はどこですか.wav" },
    eigo:              { romaji: "Eigo ga hanasemasu ka?",                   audio: "英語が話せますか.wav" },
    chottoMatte:       { romaji: "Chotto matte kudasai",                     audio: "ちょっと待ってください.wav" },
    bashoMade:         { romaji: "[Basho] made onegaishimasu",               audio: "場所までお願いします.wav" },
    bashoNanbansen:    { romaji: "[Basho] iki wa nanbansen desu ka?",        audio: "場所行きは何番線ですか？.wav" },
    denshaTomarimasu:  { romaji: "Kono densha wa [basho] ni tomarimasu ka?", audio: "この電車は場所に止まりますか.wav" },
    kaadoChaaji:       { romaji: "Kono kaado o chaaji dekimasu ka?",         audio: "このカードをチャージできますか.wav" },
    koreKudasai:       { romaji: "Kore o kudasai",                          audio: "これをください.wav" },
    ikura:             { romaji: "Ikura desu ka?",                          audio: "いくらですか.wav" },
    okaikei:           { romaji: "Okaikei onegaishimasu",                   audio: "お会計をお願いします.wav" },
    kurejitto:         { romaji: "Kurejitto kaado wa dekimasu ka?",         audio: "クレジットカードはできますか.wav" },
    atatamete:         { romaji: "Atatamete kudasai",                       audio: "温めてください.wav" },
    shichaku:          { romaji: "Shichaku dekimasu ka?",                   audio: "試着できますか.wav" },
    fukuroGoriyou:     { romaji: "Fukuro wa go-riyou desu ka?",             audio: "袋はご利用ですか.wav" },
    nanmeisama:        { romaji: "Nan-mei sama desu ka?",                   audio: "何名様ですか.wav" },
    hitori:            { romaji: "Hitori desu",                            audio: "一人です.wav" },
    futari:            { romaji: "Futari desu",                            audio: "ふたりです.wav" },
    shokuhinHaitte:    { romaji: "[Shokuhin] wa haitte imasen ka?",         audio: "食品は入っていませんか.wav" },
    bejitarian:        { romaji: "Bejitarian desu",                        audio: "ベジタリアンです.wav" },
    tasukete:          { romaji: "Tasukete",                               audio: "助けて.wav" },
    ishaHitsuyou:      { romaji: "Isha ga hitsuyou desu",                  audio: "医者が必要です.wav" },
    nakushimashita:    { romaji: "[Pasupooto / Saifu] o nakushimashita",   audio: "パスポート財布をなくしました.wav" },
    wifiArimasu:       { romaji: "Wifi wa arimasu ka?",                    audio: "ワイファイはありますか.wav" },
    genkinHaraemasu:   { romaji: "Genkin de haraemasu ka?",                audio: "現金で払えますか.wav" },
    oshiharaiDou:      { romaji: "Oshiharai wa dou nasaimasu ka?",         audio: "お支払いはどうなさいますか.wav" }
};

// ============================================================
// QUIZ QUESTIONS - each item references phrase ids from `phrases`
// above. `answer` is the correct phrase id, `options` is the full
// set of choices (correct id included) shown in randomized order.
// ============================================================
const quizData = [
    { q: "How do you say 'Good morning'?", answer: "ohayou", options: ["ohayou", "konnichiwa", "konbanwa"], tip: "Use this before noon." },
    { q: "How do you say 'Hello / good afternoon'?", answer: "konnichiwa", options: ["ohayou", "konnichiwa", "konbanwa"], tip: "The standard daytime greeting." },
    { q: "How do you say 'Good evening'?", answer: "konbanwa", options: ["ohayou", "konnichiwa", "konbanwa"], tip: "Used once the sun goes down." },
    { q: "How do you say 'Excuse me / sorry'?", answer: "sumimasen", options: ["sumimasen", "douzo", "hai"], tip: "The most versatile word in Japan - use it to apologize, get someone's attention, or say 'thanks, but no thanks.'" },
    { q: "How do you say 'Go ahead / here you go'?", answer: "douzo", options: ["sumimasen", "douzo", "hai"], tip: "Politely offer something to someone." },
    { q: "How do you say 'Yes'?", answer: "hai", options: ["hai", "iie", "sumimasen"] },
    { q: "How do you say 'No'?", answer: "iie", options: ["hai", "iie", "sumimasen"], tip: "A softer, indirect refusal (like 'daijoubu desu') is often more natural than a flat 'iie'." },
    { q: "How do you say 'It's okay / I'm fine'?", answer: "daijoubu", options: ["daijoubu", "sumimasen", "arigatou"], tip: "Useful for declining politely, e.g. when offered a bag or receipt." },
    { q: "How do you say 'Thank you' (polite)?", answer: "arigatou", options: ["arigatou", "sumimasen", "douzo"], tip: "Essential for polite interactions - a small bow while saying it goes a long way." },
    { q: "How do you say 'Please'?", answer: "onegaishimasu", options: ["onegaishimasu", "douzo", "sumimasen"], tip: "Add this after naming what you want, e.g. 'Kore o onegaishimasu.'" },
    { q: "Where is the station?", answer: "ekiDoko", options: ["ekiDoko", "eigo", "chottoMatte"], tip: "Swap 'eki' for 'toire' (restroom) or any other place name to ask the same way." },
    { q: "Do you speak English?", answer: "eigo", options: ["eigo", "ekiDoko", "chottoMatte"], tip: "Staff in tourist areas often understand basic English even if they're shy about speaking it." },
    { q: "Please wait a moment", answer: "chottoMatte", options: ["chottoMatte", "onegaishimasu", "sumimasen"] },
    { q: "To [location], please (taxi)", answer: "bashoMade", options: ["bashoMade", "ekiDoko", "chottoMatte"], tip: "Hand the driver a written address or map pin if your pronunciation is shaky." },
    { q: "Which platform for [location]?", answer: "bashoNanbansen", options: ["bashoNanbansen", "denshaTomarimasu", "kaadoChaaji"] },
    { q: "Does this train stop at [location]?", answer: "denshaTomarimasu", options: ["bashoNanbansen", "denshaTomarimasu", "kaadoChaaji"], tip: "A limited express train often needs a separate paid seat reservation." },
    { q: "Can I recharge this IC card?", answer: "kaadoChaaji", options: ["bashoNanbansen", "denshaTomarimasu", "kaadoChaaji"], tip: "Suica and PASMO can be topped up with cash at any station machine." },
    { q: "Please give me this", answer: "koreKudasai", options: ["koreKudasai", "ikura", "atatamete"], tip: "Great when pointing at an item on a menu or shelf." },
    { q: "How much?", answer: "ikura", options: ["ikura", "koreKudasai", "shichaku"], tip: "Handy at market stalls or counters with no price listed." },
    { q: "Check, please", answer: "okaikei", options: ["okaikei", "ikura", "oshiharaiDou"], tip: "Tipping is not practiced in Japan - this phrase is all you need to settle up." },
    { q: "Can I pay by credit card?", answer: "kurejitto", options: ["kurejitto", "genkinHaraemasu", "atatamete"], tip: "Cash is still widely used, especially at smaller shops and old-school restaurants." },
    { q: "Please warm it", answer: "atatamete", options: ["atatamete", "shichaku", "koreKudasai"], tip: "Common when buying konbini snacks or bento boxes." },
    { q: "Can I try this on?", answer: "shichaku", options: ["shichaku", "atatamete", "ikura"] },
    { q: "Would you like a bag?", answer: "fukuroGoriyou", options: ["fukuroGoriyou", "nanmeisama", "ikura"], tip: "Reply 'Hai, onegaishimasu' (yes please) or 'Iie, daijoubu desu' (no thanks)." },
    { q: "How many in your group?", answer: "nanmeisama", options: ["nanmeisama", "hitori", "futari"] },
    { q: "Just one", answer: "hitori", options: ["hitori", "futari", "nanmeisama"] },
    { q: "Two of us", answer: "futari", options: ["hitori", "futari", "nanmeisama"] },
    { q: "Does this contain [food]? (allergy)", answer: "shokuhinHaitte", options: ["shokuhinHaitte", "bejitarian", "sumimasen"], tip: "Say the food item where it says [Shokuhin], e.g. 'niku' for meat." },
    { q: "I'm vegetarian", answer: "bejitarian", options: ["bejitarian", "shokuhinHaitte", "sumimasen"], tip: "You can also say 'Butaniku nashi de' (without pork) for a more specific request." },
    { q: "Help!", answer: "tasukete", options: ["tasukete", "ishaHitsuyou", "sumimasen"] },
    { q: "I need a doctor", answer: "ishaHitsuyou", options: ["tasukete", "ishaHitsuyou", "nakushimashita"] },
    { q: "I lost my [passport / wallet]", answer: "nakushimashita", options: ["tasukete", "ishaHitsuyou", "nakushimashita"], tip: "Report a loss to your embassy and to the nearest police koban as soon as possible." },
    { q: "Is there wifi?", answer: "wifiArimasu", options: ["wifiArimasu", "ekiDoko", "sumimasen"], tip: "Free public wifi is patchy - most travelers rent a pocket wifi or grab an airport eSIM before arrival." },
    { q: "Can I pay by cash?", answer: "genkinHaraemasu", options: ["genkinHaraemasu", "ikura", "kurejitto"] },
    { q: "How would you like to pay? (you may hear this)", answer: "oshiharaiDou", options: ["oshiharaiDou", "ikura", "fukuroGoriyou"], tip: "Staff will often ask this at checkout - reply with 'Kurejitto kaado' or 'Genkin' (cash)." }
];
